### ISSUE TITLE
Chyba při parsování *.archimate souboru

### ISSUE THREAD

**Issue by ghost** [OPENCZEG/archimate_ikcr_motivacni_ramec#1]
![image](https://user-images.githubusercontent.com/63125023/115465850-81379c00-a22f-11eb-9682-9635e35cac3a.png)

**Comment by michalradacz** [comment]
@edu-skill-bill  Ten .archimate se neparsruje, ten jde otevřít opravdu jen v Archi, tam mi to funguje 4.8.1, - ostatní nástroje by se měly úspěšně poprat s tím .XML, to jsi zkoušel?
